### ISSUE TITLE
401 Unauthorized(Self hosted)

### ISSUE THREAD

**Issue by ernestdice** [altcha-org/forms#2]
Hello, I was trying to deploy a self-hosted server for our usage on our different registration forms,

However, I understand that the code here does not have the

`/api/v1/challenge` endpoint just like the hosted versions, I inspected the code and saw

`/api/challenge/[apiKey]`

so what I did was, I created an API key on the self hosted deployment. added the domain then pointed the challengeurl to 

![image](https://github.com/altcha-org/forms/assets/106133755/219956d6-152b-4d05-9bd8-e010f0653dc9)

I was getting 401 Unauthorized.

![image](https://github.com/altcha-org/forms/assets/106133755/1cab4589-b000-45ba-90d5-6fe3a95fd1ac)

Can you help me move forward with this? :)

Thanks!

**Comment by ovx** [comment]
Hi, thanks for trying it out and reporting. The API `/api/challenge/[apiKey]` is an old route which is not supposed to be there (removed in the last release).

The latest version `0.4.0` includes the `/api/v1/challenge` and `/api/v1/challenge/verify` endpoints which mimic the SaaS API, it should work the same way. Include the API key as query param `?apiKey=`, and  the API Key must have `AntiSpam API` feature enabled for these endpoints.

**Comment by ernestdice** [comment]
Thanks @ovx! I will try to implement the update on my deployment.

This is a great project and thank you for sharing this! I will be closing the issue already.

I hope the spam filter endpoints will be included on the future releases.
